# Generated by Django 4.2.5 on 2024-02-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default.webp', null=True, upload_to='profile_pics'),
        ),
    ]
